// Generated by gencpp from file wheel_control/wheelSpeed.msg
// DO NOT EDIT!


#ifndef WHEEL_CONTROL_MESSAGE_WHEELSPEED_H
#define WHEEL_CONTROL_MESSAGE_WHEELSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheel_control
{
template <class ContainerAllocator>
struct wheelSpeed_
{
  typedef wheelSpeed_<ContainerAllocator> Type;

  wheelSpeed_()
    : left(0.0)
    , right(0.0)
    , wheelMode(0)  {
    }
  wheelSpeed_(const ContainerAllocator& _alloc)
    : left(0.0)
    , right(0.0)
    , wheelMode(0)  {
  (void)_alloc;
    }



   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;

   typedef uint16_t _wheelMode_type;
  _wheelMode_type wheelMode;





  typedef boost::shared_ptr< ::wheel_control::wheelSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheel_control::wheelSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct wheelSpeed_

typedef ::wheel_control::wheelSpeed_<std::allocator<void> > wheelSpeed;

typedef boost::shared_ptr< ::wheel_control::wheelSpeed > wheelSpeedPtr;
typedef boost::shared_ptr< ::wheel_control::wheelSpeed const> wheelSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheel_control::wheelSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheel_control::wheelSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheel_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wheel_control': ['/home/owen/catkin_ws/src/wheel_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheel_control::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheel_control::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheel_control::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheel_control::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheel_control::wheelSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheel_control::wheelSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheel_control::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0c62b0fac850f525951f6b389829fb2";
  }

  static const char* value(const ::wheel_control::wheelSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0c62b0fac850f52ULL;
  static const uint64_t static_value2 = 0x5951f6b389829fb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheel_control::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheel_control/wheelSpeed";
  }

  static const char* value(const ::wheel_control::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheel_control::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left\n\
float32 right\n\
uint16 wheelMode\n\
";
  }

  static const char* value(const ::wheel_control::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheel_control::wheelSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.wheelMode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheelSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheel_control::wheelSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheel_control::wheelSpeed_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
    s << indent << "wheelMode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.wheelMode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEEL_CONTROL_MESSAGE_WHEELSPEED_H
